default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || 'postgres' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default
  database: identity-security-service_development

test:
  <<: *default
  database: identity-security-service_test

production:
  <<: *default
  database: identity-security-service_production
  username: identity-security-service
  password: <%= ENV['IDENTITY-SECURITY-SERVICE_DATABASE_PASSWORD'] %>
