default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: identity-security-service_development

test:
  <<: *default
  database: identity-security-service_test

production:
  <<: *default
  database: identity-security-service_production
  username: identity-security-service
  password: <%= ENV['IDENTITY-SECURITY-SERVICE_DATABASE_PASSWORD'] %>
